pages_about_me:
    path:
        en: /about-me
        pt: /{_locale}/sobre-me
    controller: App\Controller\Website\PagesController::aboutme

pages_contact:
    path:
        en: /contact
        pt: /{_locale}/contato
    controller: App\Controller\Website\PagesController::contact

pages_register:
    path:
        en: /register
        pt: /{_locale}/cadastro
    controller: App\Controller\Website\PagesController::register

post_index:
    path:
        en: /posts
        pt: /{_locale}/posts
    controller: App\Controller\Website\PostController::index

post_index_category:
    path:
        en: /posts/{category}
        pt: /{_locale}/posts/{category}
    controller: App\Controller\Website\PostController::index

security_login:
    path:
        en: /login
        pt: /{_locale}/entrar
    controller: App\Controller\Website\SecurityController::login

security_logout:
    path:     /logout
    controller: App\Controller\Website\SecurityController::logout

post_detail:
    path:     /{_locale}/{slug}
    controller: App\Controller\Website\PostController::detail

pages_homepage:
    path:
        en: /
        pt: /{_locale}/
    controller: App\Controller\Website\PagesController::homepage

