pages_about_me:
    path:
        en: /about-me
        pt: /{_locale}/sobre-me
    controller: App\Controller\Website\PagesController::aboutme

pages_contact:
    path:
        en: /contact
        pt: /{_locale}/contato
    controller: App\Controller\Website\PagesController::contact

pages_register:
    path:
        en: /register
        pt: /{_locale}/cadastro
    controller: App\Controller\Website\PagesController::register

security_login:
    path:
        en: /login
        pt: /{_locale}/entrar
    controller: App\Controller\Website\SecurityController::login

security_logout:
    path:     /logout
    controller: App\Controller\Website\SecurityController::logout

post_index:
    path:
        en: /
        pt: /{_locale}/
    controller: App\Controller\Website\PostController::index

post_detail:
    path:
        en: /{_locale}/{slug}
        pt: /{_locale}/{slug}
    controller: App\Controller\Website\PostController::detail
