pages_about_me:
    path:     /{_locale}/about-me
    controller: App\Controller\PagesController::aboutme

pages_contact:
    path:     /{_locale}/contact
    controller: App\Controller\PagesController::contact

pages_register:
  path:     /{_locale}/register
  controller: App\Controller\PagesController::register

security_login:
    path:     /login
    controller: App\Controller\SecurityController::login

security_logout:
    path:     /logout
    controller: App\Controller\SecurityController::logout

post_index:
    path:     /{_locale}/
    controller: App\Controller\PostController::index

post_detail:
    path:     /{_locale}/{slug}
    controller: App\Controller\PostController::detail
